# Generated by Django 4.2.3 on 2023-07-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('trainNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('depTime', models.DateTimeField()),
                ('seatAvailable', models.IntegerField()),
                ('acPrice', models.IntegerField()),
            ],
        ),
    ]
